### ISSUE TITLE
TODO list for plot_blocks

### ISSUE THREAD

**Issue by amanusk** [amanusk/bitcoin-tools#1]
- [x]  Control granularity of minutes

- [x] Add labels to axis

- [x] Flag to only generate CSV file

- [x] Give plots name according to file name

- [ ] Add additional tests

- [ ] Create README
